//
//  constants.swift
//  
//
//  Created by Shawn Clovie on 2023/4/15.
//

import Foundation

public enum Keys {
	public static let all = "all"
	public static let app_group = "app_group"
	public static let app_id = "app_id"
	public static let app_name = "app_name"
	public static let allow_credentials = "allow_credentials"
	public static let allowed_headers = "allowed_headers"
	public static let allowed_methods = "allowed_methods"
	public static let allowed_origin = "allowed_origin"
	public static let base_url = "base_url"
	public static let bucket = "bucket"
	public static let cache_expiration = "cache_expiration"
	public static let caller = "caller"
	public static let config = "config"
	public static let content = "content"
	public static let cors_options = "cors_options"
	public static let create_time = "create_time"
	public static let custom = "custom"
	public static let database = "database"
	public static let debug = "debug"
	public static let `default` = "default"
	public static let description = "description"
	public static let enabled = "enabled"
	public static let encryptions = "encryptions"
	public static let endpoint = "endpoint"
	public static let env = "env"
	public static let environment = "environment"
	public static let environments = "environments"
	public static let error = "error"
	public static let exposed_headers = "exposed_headers"
	public static let extra = "extra"
	public static let extra_allowed_headers = "extra_allowed_headers"
	public static let host = "host"
	public static let hosts = "hosts"
	public static let id = "id"
	public static let ip = "ip"
	public static let last_rent_time = "last_rent_time"
	public static let limit = "limit"
	public static let logger = "logger"
	public static let metric = "metric"
	public static let name = "name"
	public static let node_id = "node_id"
	public static let object_storage = "object_storage"
	public static let object_storage_ref = "object_storage_ref"
	public static let offset = "offset"
	public static let original = "original"
	public static let path = "path"
	public static let pool = "pool"
	public static let port = "port"
	public static let redis = "redis"
	public static let reuse_address = "reuse_address"
	public static let route = "route"
	public static let secret = "secret"
	public static let secret_id = "secret_id"
	public static let secret_key = "secret_key"
	public static let server = "server"
	public static let shutdown_timeout = "shutdown_timeout"
	public static let source = "source"
	public static let startup_time = "startup_time"
	public static let time_offset = "time_offset"
	public static let timezone = "timezone"
	public static let trace_id = "trace_id"
	public static let trace_dur = "trace_dur"
	public static let update_time = "update_time"
	public static let url = "url"
	public static let usage = "usage"
	public static let user_id = "user_id"
	public static let region = "region"
	public static let worker = "worker"
	public static let wrapped = "wrapped"
}
